# Generated by Django 6.0.7 on 2026-07-13 02:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('numero_factura', models.CharField(max_length=30, unique=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('ANULADA', 'Anulada')], default='REGISTRADA', max_length=15)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.proveedor')),
            ],
        ),
    ]
