# Generated by Django 6.0.7 on 2026-07-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_detallecompra_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de Caducidad')),
                ('cantidad_recibida', models.PositiveIntegerField(verbose_name='Cantidad Recibida')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='usuarios.detallecompra')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('detalle_compra', 'numero_lote'), name='unique_lote_por_detalle')],
            },
        ),
    ]
