# Generated by Django 6.0.7 on 2026-07-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.CharField(max_length=50, verbose_name='Planta')),
                ('pasillo', models.CharField(max_length=50, verbose_name='Pasillo')),
                ('estanteria', models.CharField(max_length=50, verbose_name='Estantería')),
                ('nivel', models.CharField(max_length=50, verbose_name='Nivel')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='lote',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.ubicacion', verbose_name='Ubicación'),
        ),
    ]
