# Generated by Django 6.0.7 on 2026-07-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_ubicacion_producto_stock_lote_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=10, verbose_name='Stock Mínimo'),
        ),
    ]
