# Generated by Django 6.0.7 on 2026-07-13 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_producto_stock_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('numero_factura', models.CharField(max_length=30, unique=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('ANULADA', 'Anulada')], default='REGISTRADA', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='usuarios.venta')),
            ],
        ),
    ]
